// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viexyvocqjlzuglxgrvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZXh5dm9jcWpsenVnbHhncnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjA0ODUsImV4cCI6MjA3MTI5NjQ4NX0.Q2bfueJuhcrcxU94IyBTa2C71qLWwYOBjrUI4xH8DBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});